AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31

Globals:
  Function:
    Runtime: python3.12
    Timeout: 10
    Environment:
      Variables:
        DRY_RUN: "true"          # or false, as you like
        AWS_DEFAULT_REGION: us-east-1

Resources:
  DashboardFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: main.handler      # matches your Dockerfile CMD and Mangum handler
      CodeUri: dashboard-app/backend/
      Events:
        Login:
          Type: Api
          Properties:
            Path: /login
            Method: post
        ServeLogin:
          Type: Api
          Properties:
            Path: /login
            Method: get
        StaticFiles:
          Type: Api
          Properties:
            Path: /public/{proxy+}
            Method: get
