AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31

Globals:
  Function:
    Runtime: python3.12
    Timeout: 10
    Architectures:
      - arm64  # For local Mac; change to x86_64 for AWS if desired
    Environment:
      Variables:
        DRY_RUN: "true"  # Fake DB for local testing; set to "false" for prod/DynamoDB

Resources:
  DashboardFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: main.handler  # Matches your Mangum handler in main.py
      CodeUri: dashboard-app/backend/  # Path to your backend code (main.py, etc.)
      Events:
        Api:
          Type: Api
          Properties:
            Path: /{proxy+}  # Catches all paths/methods for FastAPI (e.g., /login POST/GET, /dashboard, /public/*)
            Method: ANY
      Environment:  # Function-specific overrides
        Variables:
          SECRET_KEY: your-secure-long-random-string  # Replace with a real value (generate: python -c "import secrets; print(secrets.token_hex(32))")
          DASHBOARD_USERS_TABLE: dashboard-users
          AWS_REGION: us-east-1
      Policies:  # Add for prod DynamoDB access (optional for local)
        - DynamoDBCrudPolicy:
            TableName: dashboard-users