AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Dashboard API Stack - v0.18 (SECRET_KEY updated)

Globals:
  Function:
    Runtime: python3.12
    Timeout: 10
    Architectures:
      - x86_64
    Environment:
      Variables:
        DRY_RUN: "false"
        SECRET_KEY: 4969c4171ae050d40610358599a7d5ec05dbd8638f8f41845288a6553c3c2677
        DASHBOARD_USERS_TABLE: dashboard-users

Resources:
  DashboardFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: main.handler
      CodeUri: s3://dashboard.danieldow.com/dashboard-backend.zip
      Events:
        Api:
          Type: Api
          Properties:
            Path: /{proxy+}
            Method: ANY
      Policies:
        - Version: '2012-10-17'
          Statement:
            - Effect: Allow
              Action:
                - dynamodb:GetItem
                - dynamodb:PutItem
                - dynamodb:UpdateItem
                - dynamodb:DeleteItem
                - dynamodb:Scan
                - dynamodb:Query
              Resource: arn:aws:dynamodb:us-east-1:573978064410:table/dashboard-users

Outputs:
  ApiEndpoint:
    Description: Default execute-api endpoint
    Value: !Sub 'https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod'